common: &common
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV['DB_POOL'].present? ? "#{ENV['DB_POOL']}".to_i : 75 %>
  checkout_timeout: <%= ENV['DB_TIMEOUT'].present? ? "#{ENV['DB_TIMEOUT']}".to_i : 8 %>
  username:
  password:

development:
  <<: *common
  database: factor75_development

staging:
  url: <%= ENV['DATABASE_URL'] %>
  pool: <%= ENV['DB_POOL'].present? ? "#{ENV['DB_POOL']}".to_i : 75 %>
  checkout_timeout: <%= ENV['DB_TIMEOUT'].present? ? "#{ENV['DB_TIMEOUT']}".to_i : 8 %>

# test:
#   url: <%= ENV['DATABASE_URL'] %>
#   pool: <%= ENV['DB_POOL'].present? ? "#{ENV['DB_POOL']}".to_i : 75 %>
#   checkout_timeout: <%= ENV['DB_TIMEOUT'].present? ? "#{ENV['DB_TIMEOUT']}".to_i : 8 %>

# for local environment
test: &test
  <<: *common
  database: factor75_test

production:
  url: <%= ENV['DATABASE_URL'] %>
  pool: <%= ENV['DB_POOL'].present? ? "#{ENV['DB_POOL']}".to_i : 75 %>
  checkout_timeout: <%= ENV['DB_TIMEOUT'].present? ? "#{ENV['DB_TIMEOUT']}".to_i : 8 %>
